[package]
name = "gim"
version = "0.1.2"
edition = "2021"

[workspace]
members = [
    "material"
]

[dependencies]
image = "0.24.9"
regex = "1.10.3"
clap = { version = "4.5.1", features = ["derive"] }
material = { path = "material" }
